#:kivy 1.2.0
#:import kivy kivy
#:import win kivy.core.window

FloatLayout:
	canvas:
		Color:
			rgb: 1, 1, 1
		Rectangle:
			source: 'media/images/gw_python.png'
			size: self.size
			
	BoxLayout:
		padding: 10
		spacing: 10
		size_hint: 1, None
		pos_hint: {'top': 1}
		height: 44

<TouchObject>
	on_size: self.center = win.Window.center
	size_hint: None, None
	canvas:
		Color:
			rgba: (.8,.8,.8,.75)